### ISSUE TITLE
Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by budda85** [FriedrichFroebel/brother_ql_web#4]
Hey, i try to use your fork, but when i start i have an Error in my browser:

> Error: 500 Internal Server Error

>Sorry, the requested URL 'http://192.168.10.159:8013/labeldesigner' caused an error:

>Internal Server Error

Here are my Logs.
What do i wrong?

> (.brother_ql_pip) pi@raspi-Keller:~/brother_ql_webOrg $ brother_ql_web --configuration config.json tcp://192.168.10.159:9100
deprecation warning: brother_ql.devicedependent is deprecated and will be removed in a future release
Bottle v0.12.25 server starting up (using WSGIRefServer())...
Listening on http://192.168.10.159:8013/
Hit Ctrl-C to quit.
Traceback (most recent call last):
  File "/home/pi/brother_ql_web/.brother_ql_pip/bin/bottle.py", line 876, in _handle
    return route.call(**args)
           ^^^^^^^^^^^^^^^^^^
  File "/home/pi/brother_ql_web/.brother_ql_pip/bin/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
         ^^^^^^^^^^^^^^^^^^
  File "/home/pi/brother_ql_web/.brother_ql_pip/bin/bottle.py", line 3692, in wrapper
    return template(tpl_name, **tplvars)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/brother_ql_web/.brother_ql_pip/bin/bottle.py", line 3668, in template
    return TEMPLATES[tplid].render(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/brother_ql_web/.brother_ql_pip/bin/bottle.py", line 3380, in render
    return self.tpl.render(**_defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/brother_ql_web/.brother_ql_pip/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/pi/brother_ql_web/.brother_ql_pip/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "<template>", line 34, in top-level template code
  File "<template>", line 54, in block 'content'
  File "/home/pi/brother_ql_web/.brother_ql_pip/lib/python3.11/site-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
           ~~~^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'brother_ql_web.configuration.LabelConfiguration object' has no attribute 'DEFAULT_FONTS'
192.168.10.218 - - [15/Aug/2023 21:50:39] "GET /labeldesigner HTTP/1.1" 500 759

**Comment by budda85** [comment]
Okay, sorry.
I have made a second attempt and now i see the Web interface.
But when i ty to print, i have this problem with the 'variable red'

> Traceback (most recent call last):
  File "/home/pi/brother_ql_web/.brother_ql_pip/lib/python3.11/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
           ^^^^^^^^^^^^^^^^^^
  File "/home/pi/brother_ql_web/.brother_ql_pip/lib/python3.11/site-packages/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
         ^^^^^^^^^^^^^^^^^^
  File "/home/pi/brother_ql_web/.brother_ql_pip/lib/python3.11/site-packages/brother_ql_web/web.py", line 118, in print_text
    qlr = generate_label(
          ^^^^^^^^^^^^^^^
  File "/home/pi/brother_ql_web/.brother_ql_pip/lib/python3.11/site-packages/brother_ql_web/labels.py", line 220, in generate_label
    red=red,
        ^^^
UnboundLocalError: cannot access local variable 'red' where it is not associated with a value
192.168.10.218 - - [17/Aug/2023 16:00:06] "POST /api/print/text HTTP/1.1" 500 760

My config:

> {
  "server": {
    "port": 8013,
    "host": "",
    "log_level": "WARNING",
    "additional_font_folder": ""
  },
  "printer": {
    "model": "QL-720NW",
    "printer": "tcp://192.168.10.110"
  },
  "label": {
    "default_size": "62",
    "default_orientation": "standard",
    "default_font_size": 70,
    "default_fonts": [
      {"family": "Minion Pro",      "style": "Semibold"},
      {"family": "Linux Libertine", "style": "Regular"},
      {"family": "DejaVu Serif",    "style": "Book"}
    ]
  },
  "website": {
    "html_title": "Label Designer",
    "page_title": "Brother QL Label Designer",
    "page_headline": "Design your label and print it…"
  }
}

**Comment by FriedrichFroebel** [comment]
Sorry for the delay - this issue somehow got lost in my e-mails.

Thank you for the report. I have just pushed a printing fix to GitHub. For the other issue, you apparently managed to fix this yourself?
